site_name: Emperium Wiki
docs_dir: "docs"
copyright: Feito com ❤️ pelo time Emperium.
site_author: Emperium
site_url: https://emp-interactive.github.io/wiki/
repo_name: Emp-Interactive/wiki
repo_url: https://github.com/Emp-Interactive/wiki

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  font:
    text: "Segoe UI"
    code: "Roboto Mono"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: black
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: indigo
  highlightjs: true
  hljs_languages:
    - yaml
    - json
  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - content.code.copy

plugins:
  - search
  - glightbox
  - minify:
      minify_html: true
  - social:
      cards: true
      cards_layout_options:
        font_family: Roboto
  - i18n:
      default_language: pt
      languages:
        pt: Português
        es: Español
        en: English
      docs_structure: folder

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Emp-Interactive/wiki

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html  

extra_javascript:
  - https://cdn.jsdelivr.net/npm/@glidejs/glide

nav:
  pt:
    - Sobre o Servidor: pt/about/index.md
    - Sistemas do Servidor: pt/systems/index.md
    - Principais NPCs: pt/npcs/index.md
    - Instâncias: pt/instances/index.md
    - Guias e Suporte: pt/support/index.md
    - FAQ: pt/faq.md
    - Termos de Uso: pt/terms.md
  es:
    - Sobre el Servidor: es/about/index.md
    - Sistemas del Servidor: es/systems/index.md
    - NPCs Principales: es/npcs/index.md
    - Instancias: es/instances/index.md
    - Guías y Soporte: es/support/index.md
    - Preguntas Frecuentes (FAQ): es/faq.md
    - Términos de Uso: es/terms.md