name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: read

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout main
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs-material==9.5.21 \
            mkdocs-include-markdown-plugin==6.0.6 \
            mkdocs-awesome-pages-plugin==2.9.2 \
            mkdocs-glightbox==0.4.0 \
            mkdocs-minify-plugin==0.8.0 \
            mkdocs-material-extensions==1.3.1 \
            pillow==11.1.0 \
            cairosvg==2.7.1 

      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - run: mkdocs gh-deploy --force
        working-directory: ./docs